### PR TITLE
Add an option to disable background color

### PR DESCRIPTION
**Pull request by AlexLov**

### CODE REVIEW

**Comment by diniamo** [comment]
https://www.reddit.com/r/neovim/comments/3v06lo/making_the_background_transparent/
or if the above doesn't work:
https://forum.archlabslinux.com/t/make-vim-background-transparent-so-you-can-see-terminal/5023

imo it's not the plugins job to manage the background color

**Comment by AlexLov** [comment]
But the plugin still manage background color so why not to add the option? 
It's not quite convenient to override all the highlight groups declared in the plugin just to disable background color, it's just much easier to do it in the plugin's code.
And yes it actually does what described in those links, and a little bit more.

**Comment by diniamo** [comment]
I know what it does, I looked at the code.

If it's better managed by the plugin, then why don't most themes do it?

**Comment by mngshm** [comment]
How many user's would override Everblush background or make it transperant? As far as I know most user's would use the default Everblush background.

**Comment by mngshm** [comment]
@AlexLov reply me whenever you're free.

**Comment by AlexLov** [comment]
@Mangeshrex at least one user (me) will use it. And I’m fine to have it in my fork if you against this.

**Pull request merged**
